# Site settings
title: Jordan D. Snyder
email: jordandanielsnyder@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Doctoral candidate in clinical psychology interested in global mental health,
  social processes, and community-based work with conflict-affected populations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  jordandsnyder
rss: y

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Doctoral Candidate"
excerpt_separator: "<!--more-->"

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-66601076-1

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: jordandsnyder

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
gems:
 - jekyll-feed
